name: Test action
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@v1.3.1
    - uses: actions/checkout@v3
    - uses: ./
      with:
        vm_image: ${{ secrets.VM_IMAGE }}
        vm_image_sha256: ${{ secrets.VM_IMAGE_SHA256 }}
        ssh_key: ${{ secrets.VM_KEY }}
    - shell: macppc {0}
      run: |
        whoami
        uname -a
        date
