name: Test action
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test_simple:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
        sudo dpkg-reconfigure man-db
    - uses: jlumbroso/free-disk-space@v1.3.1
    - uses: actions/checkout@v3
    - uses: ./
      with:
        vm_image: ${{ secrets.VM_IMAGE }}
        vm_image_sha256: ${{ secrets.VM_IMAGE_SHA256 }}
        ssh_key: ${{ secrets.VM_KEY }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        s3_endpoint_url: ${{ secrets.S3_ENDPOINT }}
    - shell: macppc {0}
      run: |
        whoami
        uname -a
        date
